export const chats = [
  {
    id: 1,
    thumbnail: "./assets/img/person-1.png",
    name: "John Doe",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: true,
  },
  {
    id: 2,
    thumbnail: "./assets/img/person-2.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: false,
  },
  {
    id: 3,
    thumbnail: "./assets/img/person-3.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: true,
  },
  {
    id: 4,
    thumbnail: "./assets/img/person-1.png",
    name: "Kunle Adekunle",
    content: "Hello Janet, thank you for reaching out",
    date: "12:07am",
    read: false,
  },
  {
    id: 5,
    thumbnail: "./assets/img/person-2.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: false,
  },
  {
    id: 6,
    thumbnail: "./assets/img/person-3.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: false,
  },
  {
    id: 7,
    thumbnail: "./assets/img/person-1.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: true,
  },
  {
    id: 8,
    thumbnail: "./assets/img/person-2.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: true,
  },
  {
    id: 9,
    thumbnail: "./assets/img/person-3.png",
    name: "Kunle Adekunle",
    content: "Hello, I want to make enquiries about your product",
    date: "12:07am",
    read: true,
  },
];
